spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_card
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
      host: smtp.gmail.com
      port: 587
      username: tjonibek2001@gmail.com
      password: iuyk zyaw dway yjgn
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            ssl:
              trust: smtp.gmail.com

